   <div style="margin-top: 30px">
        <!-- Page Content -->
        <div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <div class="login-panel panel panel-default">
                            <div class="panel-heading frame logo-center-form" id="container">
                                <img src="/images/login.jpg" class="img-responsive" alt="Logo">
                            </div>
                            <?php if( isset($this->error) ):?>
                            <div class="panel-body">
	                            <div role="alert" class="alert alert-danger">
	                                <?php echo $this->error ?>
	                            </div>
                            </div>
                            <?php endif;?>
                            <div class="panel-body">
                                <form method="post" action="">
                                    <div class="form-group">
                                        <input class="form-control input-lg" type="email" name="usrEmail" value="<?php echo isset($this->email) ? $this->email : ''?>" required="required" placeholder="email">
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control input-lg" type="password" name="usrPassword" required="required" placeholder="password...">
                                    </div>
                                    <div class="checkbox small">
                                        <label>
										<!-- <input type="checkbox"> recordar credenciales? -->
                                        </label>
                                    </div>
                                    <button type="submit" class="current-parent btn btn-block btn-lg btn-primary">Enter</button>
                                </form>
                            </div>
                            <div class="panel-footer">
                            	<a class="pull-right " href="<?php echo $this->url(array('controller'=>'users', 'action'=>'add')); ?>">Sign up</a>
                            	<div class="clearfix"></div>
                            </div>
                        </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>	