	<div id="wrapper" class="margin-top-15">
        <!-- Page Content -->
        <div id="page-wrapper" class="background-page">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="login-panel panel panel-default">
                            <div class="panel-heading frame logo-center-form" id="container">
                                 <img src="/images/retesar-logo-main.png" class="center-logo" alt="Logo">
                            </div>
                            <div class="panel-body">
                                <h1 class="text-center">Error: 401, Permiso denegado</h1>
                                <p>
								Está tratando de acceder a un recurso que esta protegido o su sesión ha expirado.</p>
								<br>

                                <form>
                                    <a href="/" class="current-parent btn btn-block btn-lg btn-danger"><span class="fa fa-fw fa-long-arrow-left"> </span> Volver al inicio</a>
                                </form>
                            </div>
                            <div class="panel-footer">

                            </div>
                        </div>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>