<div class="row">
	<div class="col-md-12">
		<h2>Add</h2>   
    </div>
</div>
<hr />
<div class="row">
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
		            	User data
		            </div>
		            <div class="panel-body">
		            	<form role="form" action="" method="post">
							<div class="form-group">
                            	<label>Name</label>
                                <input class="form-control" type="text" name="usrName" value=""  placeholder="your name" required="required" />
                            </div>
							<div class="form-group">
                            	<label>Last Name</label>
                                <input class="form-control" type="text" name="usrLastName" value=""  placeholder="your last name" required="required" />
                            </div>
							<div class="form-group">
                            	<label>Phone Number</label>
                                <input class="form-control" type="text" name="usrPhone" value=""  placeholder="your phone number" required="required" />
                            </div>
							<div class="form-group">
                            	<label>Email</label>
                                <input class="form-control" type="email" name="usrEmail" value=""  placeholder="your email" required="required" />
                            </div>                            
							<div class="form-group">
                            	<label>Password</label>
                                <input class="form-control" type="password" name="usrPassword" value=""  placeholder="" />
                            </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
		            </div>
		        </div>
		     </div>
		 </div>
	</div>
</div>



